services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    container_name: worktrack-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-worktrackdb}
      POSTGRES_USER: ${DB_USERNAME:-worktrack}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - worktrack-network

  # Spring Boot Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: worktrack-backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:postgresql://db:5432/${DB_NAME:-worktrackdb}
      DB_USERNAME: ${DB_USERNAME:-worktrack}
      DB_PASSWORD: ${DB_PASSWORD:-changeme}
      JWT_SECRET: ${JWT_SECRET:-worktrack2025secretkeymustbelongenoughforhs512algorithm}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-86400000}
    networks:
      - worktrack-network

  # React Frontend + Nginx
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: worktrack-frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST:-worktrack.example.com}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST:-worktrack.example.com}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-admin@example.com}
    networks:
      - worktrack-network
      - nginx-proxy
    expose:
      - "80"

networks:
  worktrack-network:
    driver: bridge
  nginx-proxy:
    external: true

volumes:
  postgres_data:
    driver: local